version: '3'
services:
  user_management_service:
    container_name: user_management_service
    build: 
      context: .
      dockerfile: ./user_management_service/Dockerfile
    environment:
      - NODE_ENV=production
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181 
    ports:
      - "3000:3000"  
    depends_on:
      - mongo
      - kafka
  metadata_management_service:
    container_name: metadata_management_service
    build: 
      context: .
      dockerfile: ./metadata_management_service/Dockerfile
    environment:
      - NODE_ENV=production
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181 
    ports:
      - "3001:3001"
    depends_on:
      - mongo
      - kafka
  directory_management_service:
    container_name: directory_management_service
    build: 
      context: .
      dockerfile: ./directory_management_service/Dockerfile
    environment:
      - NODE_ENV=production
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181 
    ports:
      - "3002:3002"
    depends_on:
      - mongo
      - metadata_management_service
      - kafka
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27016:27017"
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka  
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: sales-topic:1:1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - 9092:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock