enum EventTypeModel {
    CREATE_USER = 'CREATE_USER',
    UPDATE_USER = 'UPDATE_USER',
    DELETE_USER = 'DELETE_USER',
    CREATE_METADATA = 'CREATE_METADATA',
    UPDATE_METADATA = 'UPDATE_METADATA',
    DELETE_METADATA = 'DELETE_METADATA',
    CREATE_DIRECTORY = 'CREATE_DIRECTORY',
    UPDATE_DIRECTORY = 'UPDATE_DIRECTORY',
    DELETE_DIRECTORY = 'DELETE_DIRECTORY',
    ADDED_FILES = 'ADDED_FILES',
    DELETED_FILES = 'DELETED_FILES'
}

export default EventTypeModel;